### ISSUE TITLE
Jeg vil belære deg om vår allmektige fader Graphviz

### ISSUE THREAD

**Issue by pbsds** [halworsen/emnestigen#1]
Den er lett å legge til i form av `Viz.js`, og kan bl.a. garantere at ingen kanter vil kollidere med andre noder.

Eksempel:

https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%20%20%20%20%0A%20%20%20%20node%20%5Bstyle%3Dfilled%2C%20shape%3Dcircle%2C%20color%3DSpringGreen%5D%0A%20%20%20%20edge%20%5Bdir%3Dnone%5D%0A%20%20%20%20%0A%20%20%20%20TMA4267%20-%3E%20TMA4285%0A%20%20%20%20TMA4265%20-%3E%20TMA4285%0A%20%20%20%20TMA4245%20-%3E%20TMA4285%0A%20%20%20%20%0A%7D

**Comment by halworsen** [comment]
Ooo, den så jækla snasen ut! Akkurat nå bruker jeg (og har blitt litt forelska i) [react-d3-graph](https://www.npmjs.com/package/react-d3-graph) fordi den har stor støtte for interaktivitet, men en mulighet til å bytte mellom Graphviz og d3 hadde vært kult

**Comment by halworsen** [comment]
Vakkert 😍 

![image](https://user-images.githubusercontent.com/9088854/68027919-e30aeb80-fcb3-11e9-98e3-857ece32ae73.png)

**Comment by halworsen** [comment]
Nå er muligheten for å bytte mellom react-d3-graph og graphviz med 😃
